<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data_kabupaten = [
            [
                'nama_kabupaten' => 'Pacitan',
                'latitude' => '-8.180641905',
                'longitude' => '111.110465',
                'bobot_ahp'=>'0.0325',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0209',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0209',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Ponorogo',
                'latitude' => '-7.865551273',
                'longitude' => '111.466938',
                'bobot_ahp'=>'0.0597',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0261',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0261',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Trenggalek',
                'latitude' => '-7.866367973',
                'longitude' => '111.4668488',
                'bobot_ahp'=>'0.0623',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0290',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0290',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Tulungagung',
                'latitude' => '-8.090863592',
                'longitude' => '111.966489',
                'bobot_ahp'=>'0.0142',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0251',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0251',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Blitar',
                'latitude' => '-8.178916132',
                'longitude' => '112.3120825',
                'bobot_ahp'=>'0.0157',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0268',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0268',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Kediri',
                'latitude' => '-7.765510344',
                'longitude' => '112.1988415',
                'bobot_ahp'=>'0.0163',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0275',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0275',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Malang',
                'latitude' => '-8.223454573',
                'longitude' => '112.5245813',
                'bobot_ahp'=>'0.0614',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0535',
                'color_fuzzy'=>'#d64545',
                'status_fuzzy'=>'Tinggi',
                'bobot_fahp'=>'0.0535',
                'color_fahp'=>'#d64545',
                'status_fahp'=>'Tinggi',
            ],
            [
                'nama_kabupaten' => 'Lumajang',
                'latitude' => '-8.127078856',
                'longitude' => '113.2330116',
                'bobot_ahp'=>'0.0385',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0277',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0277',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Jember',
                'latitude' => '-8.173174838',
                'longitude' => '113.7012749',
                'bobot_ahp'=>'0.0918',
                'color_ahp'=>'#d64545',
                'status_ahp'=>'Tinggi',
                'bobot_fuzzy'=>'0.0622',
                'color_fuzzy'=>'#d64545',
                'status_fuzzy'=>'Tinggi',
                'bobot_fahp'=>'0.0622',
                'color_fahp'=>'#d64545',
                'status_fahp'=>'Tinggi',
            ],
            [
                'nama_kabupaten' => 'Banyuwangi',
                'latitude' => '-8.217195459',
                'longitude' => '114.3855275',
                'bobot_ahp'=>'0.0454',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0510',
                'color_fuzzy'=>'#d64545',
                'status_fuzzy'=>'Tinggi',
                'bobot_fahp'=>'0.0510',
                'color_fahp'=>'#d64545',
                'status_fahp'=>'Tinggi',
            ],
            [
                'nama_kabupaten' => 'Bondowoso',
                'latitude' => '-7.913755887',
                'longitude' => '113.8288521',
                'bobot_ahp'=>'0.0183',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0298',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0298',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Situbondo',
                'latitude' => '-7.70355413',
                'longitude' => '114.0115975',
                'bobot_ahp'=>'0.0463',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0365',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0365',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Probolinggo',
                'latitude' => '-7.761205073',
                'longitude' => '113.1875188',
                'bobot_ahp'=>'0.0443',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0342',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0342',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Pasuruan',
                'latitude' => '-7.602194313',
                'longitude' => '112.7769398',
                'bobot_ahp'=>'0.0250',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0373',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0373',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Sidoarjo',
                'latitude' => '-7.446396954',
                'longitude' => '112.7070186',
                'bobot_ahp'=>'0.0241',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0270',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0270',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Mojokerto',
                'latitude' => '-7.531500741',
                'longitude' => '112.4851305',
                'bobot_ahp'=>'0.0170',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0190',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0190',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Jombang',
                'latitude' => '-7.550781933',
                'longitude' => '112.2328855',
                'bobot_ahp'=>'0.0136',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0287',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0287',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Nganjuk',
                'latitude' => '-7.603746849',
                'longitude' => '111.9027148',
                'bobot_ahp'=>'0.0616',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0283',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0283',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',

            ],
            [
                'nama_kabupaten' => 'Madiun',
                'latitude' => '-7.621324159',
                'longitude' => '111.6321856',
                'bobot_ahp'=>'0.0109',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0209',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0209',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',

            ],
            [
                'nama_kabupaten' => 'Magetan',
                'latitude' => '-7.653700388',
                'longitude' => '111.3319861',
                'bobot_ahp'=>'0.0316',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0200',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0200',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',

            ],
            [
                'nama_kabupaten' => 'Ngawi',
                'latitude' => '-7.406891207',
                'longitude' => '111.4325328',
                'bobot_ahp'=>'0.0109',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0214',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0214',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',

            ],
            [
                'nama_kabupaten' => 'Bojonegoro',
                'latitude' => '-7.124751256',
                'longitude' => '111.7960578',
                'bobot_ahp'=>'0.0168',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0281',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0281',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Tuban',
                'latitude' => '-6.894643815',
                'longitude' => '112.0421795',
                'bobot_ahp'=>'0.0138',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0247',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0247',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Lamongan',
                'latitude' => '-7.110688181',
                'longitude' => '112.44014',
                'bobot_ahp'=>'0.0105',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0118',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0118',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Gresik',
                'latitude' => '-7.165512004',
                'longitude' => '112.6525875',
                'bobot_ahp'=>'0.0199',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0315',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0315',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Bangkalan',
                'latitude' => '-7.025405731',
                'longitude' => '112.7552868',
                'bobot_ahp'=>'0.0105',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0209',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0209',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Sampang',
                'latitude' => '-7.190362858',
                'longitude' => '113.2533737',
                'bobot_ahp'=>'0.0103',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0208',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0208',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Pamekasan',
                'latitude' => '-7.153779601',
                'longitude' => '113.4724685',
                'bobot_ahp'=>'0.0079',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0089',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0089',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Sumenep',
                'latitude' => '-7.009649999',
                'longitude' => '113.8597443',
                'bobot_ahp'=>'0.0155',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0265',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0265',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Kota Kediri',
                'latitude' => '-7.847858057',
                'longitude' => '112.0179011',
                'bobot_ahp'=>'0.0141',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0250',
                'color_fuzzy'=>'#d4cc39',
                'status_fuzzy'=>'Sedang',
                'bobot_fahp'=>'0.0250',
                'color_fahp'=>'#d4cc39',
                'status_fahp'=>'Sedang',
            ],
            [
                'nama_kabupaten' => 'Kota Blitar',
                'latitude' => '-8.095379362',
                'longitude' => '112.1602692',
                'bobot_ahp'=>'0.0065',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0164',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0164',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Kota Malang',
                'latitude' => '-7.964943232',
                'longitude' => '112.6444619',
                'bobot_ahp'=>'0.0115',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0130',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0130',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Kota Probolinggo',
                'latitude' => '-7.775877677',
                'longitude' => '113.2076489',
                'bobot_ahp'=>'0.0053',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0059',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0059',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Kota Pasuruan',
                'latitude' => '-7.646705444',
                'longitude' => '112.903232',
                'bobot_ahp'=>'0.0050',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0056',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0056',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Kota Mojokerto',
                'latitude' => '-7.470571271',
                'longitude' => '112.4409152',
                'bobot_ahp'=>'0.0060',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0159',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0159',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Kota Madiun',
                'latitude' => '-7.630566402',
                'longitude' => '111.531478',
                'bobot_ahp'=>'0.0309',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0192',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0192',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
            [
                'nama_kabupaten' => 'Kota Surabaya',
                'latitude' => '-7.206449001',
                'longitude' => '112.8246079',
                'bobot_ahp'=>'0.0407',
                'color_ahp' =>'#d4cc39',
                'status_ahp'=>'Sedang',
                'bobot_fuzzy'=>'0.0549',
                'color_fuzzy'=>'#d64545',
                'status_fuzzy'=>'Tinggi',
                'bobot_fahp'=>'0.0549',
                'color_fahp'=>'#d64545',
                'status_fahp'=>'Tinggi',
            ],
            [
                'nama_kabupaten' => 'Kota Batu',
                'latitude' => '-7.882862609',
                'longitude' => '112.5329899',
                'bobot_ahp'=>'0.0332',
                'color_ahp' =>'#32c256',
                'status_ahp'=>'Rendah',
                'bobot_fuzzy'=>'0.0218',
                'color_fuzzy'=>'#32c256',
                'status_fuzzy'=>'Rendah',
                'bobot_fahp'=>'0.0218',
                'color_fahp'=>'#32c256',
                'status_fahp'=>'Rendah',
            ],
        ];

        DB::table('kabupaten')->insert($data_kabupaten);
    }
}
